<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-21TTL97P" failures="2" tests="2" name="Test" time="4.418" errors="0" timestamp="23 Apr 2023 07:26:39 GMT">
  <testcase classname="TestCases.LoginTest" name="Negative" time="0.093">
    <failure type="com.codoid.products.exception.FilloException" message="data table is not found">
      <![CDATA[com.codoid.products.exception.FilloException: data table is not found
at com.codoid.products.fillo.SelectExcelUtil.runSelectQuery(SelectExcelUtil.java:57)
at com.codoid.products.fillo.Select.getRecordset(Select.java:61)
at com.codoid.products.fillo.Connection.executeQuery(Connection.java:64)
at TestCases.LoginTest.Negative(LoginTest.java:39)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Negative -->
  <testcase classname="TestCases.LoginTest" name="Positive" time="0.001">
    <failure type="com.codoid.products.exception.FilloException" message="data table is not found">
      <![CDATA[com.codoid.products.exception.FilloException: data table is not found
at com.codoid.products.fillo.SelectExcelUtil.runSelectQuery(SelectExcelUtil.java:57)
at com.codoid.products.fillo.Select.getRecordset(Select.java:61)
at com.codoid.products.fillo.Connection.executeQuery(Connection.java:64)
at TestCases.LoginTest.Positive(LoginTest.java:18)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Positive -->
</testsuite> <!-- Test -->
